version: '3.7'


#     ██████╗ ██████╗ ██████╗ ███████╗██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗
#    ██╔════╝██╔═══██╗██╔══██╗██╔════╝██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║
#    ██║     ██║   ██║██║  ██║█████╗  ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║
#    ██║     ██║   ██║██║  ██║██╔══╝  ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║
#    ╚██████╗╚██████╔╝██████╔╝███████╗███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║
#     ╚═════╝ ╚═════╝ ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝

services:

  codelaunch:
    depends_on:
      - admin
      - queue
    image: ${IMAGE:-registry.gitlab.com/vitruviantech/codelaunch/platform}:${VERSION:-2023.0.0-rc.1}
    # tty: true
    stdin_open: true
    ports:
      - "${PORT:-3000}:80"
      - "${LIBRARY_PORT:-3001}:3001"
      - "${DEV_PORT:-24678}:${DEV_PORT:-24678}"
    env_file:
      - .env
    environment:
      ENV: development
      VERBOSE: ${VERBOSE:-}
      DEBUG: ${DEBUG:-graphile-build:warn,postgraphile:postgres:error}  # Postgraphile debugging (https://www.graphile.org/postgraphile/debugging/#via-debug-envvar)
      PORT: ${PORT:-3000}
      DEV_PORT: ${DEV_PORT:-24678}
      DATABASE_SOURCE_URL: postgresql://postgres@source/postgres
      DATABASE_TARGET_URL: postgresql://postgres@target/postgres
      QUEUE_URL: queue
    volumes:
      - /srv/codelaunch/node_modules
      - ./.env:/srv/codelaunch/.env
      - ./context:/srv/codelaunch/context
      - ./config.ts:/srv/codelaunch/config.ts
      - ./tsconfig.json:/srv/codelaunch/tsextends.json
      - ./codegen.yml:/srv/codelaunch/codegen.yml
      - ./jobs.json:/srv/codelaunch/jobs.json
      - ./package.json:/srv/codelaunch/context.json
      - ./output:/srv/codelaunch/.output
      - ./nginx.conf:/etc/nginx/nginx.conf
      ########################################################################################
      # ============================ APP DEVELOPMENT REGISTRATION ============================
      #
      # Notes:
      # 1. Add (clone/check out) applications under host ./apps directory
      # 2. Mount each application to container /srv/codelaunch/apps/${app} directory
      # 3. $app can be any string; simple int incrementing is suggested (i.e.: 0, 1, 2...n)
      # 4. Mounted subdirectory must be directly under /srv/codelaunch/apps
      #    (i.e., /srv/codelaunch/apps/foo/bar not supported)
      # 5. *DO NOT* mount ./apps directly to /srv/codelaunch/apps: CodeLaunch ships with a
      #    "core" app that is already installed in the container's "apps" directory (and
      #    would get overridden if mounting the entire ./apps directory)
      # 6. For more information from our customer support, please run `yarn codelaunch info`
      #
      # Examples:
      # - ./apps/example/foo:/srv/codelaunch/apps/0
      # - ./apps/foo:/srv/codelaunch/apps/1
      # - ./apps/foo/bar/baz:/srv/codelaunch/apps/2
      #
      ########################################################################################
      - ./apps/app:/srv/codelaunch/apps/0

  source:
    image: vitruviantech/postgis:13-master
    command: ["postgres", "-c", "work_mem=64MB", "-c", "max_connections=15", "-c", "shared_buffers=500MB"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /var/lib/postgresql/data

  target:
    image: vitruviantech/postgis:13-master
    command: ["postgres", "-c", "work_mem=64MB", "-c", "max_connections=15", "-c", "shared_buffers=500MB"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /opt/postgresql/data

  admin:
    depends_on:
      - source
      - target
    image: dpage/pgadmin4
    ports:
      - "${ADMIN_PORT:-3002}:80"
    environment:
      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: 0
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres@codelaun.ch}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-1337}
    volumes:
      - admin:/var/lib/pgadmin

  queue:
    image: redis:alpine
    command: redis-server --loglevel warning
    volumes:
      - /data

volumes:
  admin:
